package wgcf

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/webstudiobond/mihomo-warp-proxy/internal/config"
)

// sampleProfile is a representative wgcf-profile.conf as generated by wgcf.
const sampleProfile = `[Interface]
PrivateKey = YH2h2kSHzMaAgBNiNWuMEljlKGsaVKnv+hFtZOZEEEE=
Address = 172.16.0.2/32,2606:4700:110:8949:fed8:548c:4603:5b00/128
DNS = 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
MTU = 1280

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0,::/0
Endpoint = engage.cloudflareclient.com:2408
`

func TestParseINI(t *testing.T) {
	p, err := parseINI(sampleProfile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if p.PrivateKey != "YH2h2kSHzMaAgBNiNWuMEljlKGsaVKnv+hFtZOZEEEE=" {
		t.Errorf("PrivateKey: got %q", p.PrivateKey)
	}
	if p.PublicKey != "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=" {
		t.Errorf("PublicKey: got %q", p.PublicKey)
	}
	if p.IPv4 != "172.16.0.2" {
		t.Errorf("IPv4: got %q, want %q", p.IPv4, "172.16.0.2")
	}
	if p.IPv6 != "2606:4700:110:8949:fed8:548c:4603:5b00" {
		t.Errorf("IPv6: got %q, want %q", p.IPv6, "2606:4700:110:8949:fed8:548c:4603:5b00")
	}
}

func TestParseINICommentAndBlankLines(t *testing.T) {
	content := `
# This is a comment
[Interface]
# Another comment
PrivateKey = YH2h2kSHzMaAgBNiNWuMEljlKGsaVKnv+hFtZOZEEEE=
Address = 172.16.0.2/32,2606:4700:110:8949:fed8:548c:4603:5b00/128

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
`
	p, err := parseINI(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.PrivateKey == "" || p.PublicKey == "" {
		t.Error("keys not parsed when comments and blank lines present")
	}
}

func TestSplitAddresses(t *testing.T) {
	cases := []struct {
		name    string
		input   string
		wantV4  string
		wantV6  string
		wantErr bool
	}{
		{
			name:   "standard wgcf output",
			input:  "172.16.0.2/32,2606:4700:110:8949:fed8:548c:4603:5b00/128",
			wantV4: "172.16.0.2",
			wantV6: "2606:4700:110:8949:fed8:548c:4603:5b00",
		},
		{
			name:   "addresses with spaces",
			input:  " 172.16.0.2/32 , 2606:4700::1/128 ",
			wantV4: "172.16.0.2",
			wantV6: "2606:4700::1",
		},
		{
			name:    "missing ipv4",
			input:   "2606:4700::1/128",
			wantErr: true,
		},
		{
			name:    "missing ipv6",
			input:   "172.16.0.2/32",
			wantErr: true,
		},
		{
			name:    "empty string",
			input:   "",
			wantErr: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			v4, v6, err := splitAddresses(tc.input)
			if tc.wantErr {
				if err == nil {
					t.Errorf("expected error, got nil (v4=%q v6=%q)", v4, v6)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if v4 != tc.wantV4 {
				t.Errorf("IPv4: got %q, want %q", v4, tc.wantV4)
			}
			if v6 != tc.wantV6 {
				t.Errorf("IPv6: got %q, want %q", v6, tc.wantV6)
			}
		})
	}
}

func TestValidateProfile(t *testing.T) {
	validKey := "YH2h2kSHzMaAgBNiNWuMEljlKGsaVKnv+hFtZOZEEEE="

	cases := []struct {
		name    string
		p       Profile
		wantErr bool
	}{
		{
			name: "valid profile",
			p: Profile{
				PrivateKey: validKey,
				PublicKey:  "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
				IPv4:       "172.16.0.2",
				IPv6:       "2606:4700::1",
			},
		},
		{
			name: "private key too short",
			p: Profile{
				PrivateKey: "tooshort",
				PublicKey:  "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
				IPv4:       "172.16.0.2",
				IPv6:       "2606:4700::1",
			},
			wantErr: true,
		},
		{
			name: "public key too short",
			p: Profile{
				PrivateKey: validKey,
				PublicKey:  "tooshort",
				IPv4:       "172.16.0.2",
				IPv6:       "2606:4700::1",
			},
			wantErr: true,
		},
		{
			name: "missing ipv4",
			p: Profile{
				PrivateKey: validKey,
				PublicKey:  "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
				IPv4:       "",
				IPv6:       "2606:4700::1",
			},
			wantErr: true,
		},
		{
			name: "missing ipv6",
			p: Profile{
				PrivateKey: validKey,
				PublicKey:  "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
				IPv4:       "172.16.0.2",
				IPv6:       "",
			},
			wantErr: true,
		},
		{
			name: "invalid character in key",
			p: Profile{
				PrivateKey: "YH2h2kSHzMaAgBNiNWuMEljlKGsaVKnv+hFtZOZ!!!!",
				PublicKey:  "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
				IPv4:       "172.16.0.2",
				IPv6:       "2606:4700::1",
			},
			wantErr: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validateProfile(&tc.p)
			if tc.wantErr && err == nil {
				t.Errorf("expected error, got nil")
			}
			if !tc.wantErr && err != nil {
				t.Errorf("unexpected error: %v", err)
			}
		})
	}
}

func TestFileExists(t *testing.T) {
	dir := t.TempDir()

	existing := filepath.Join(dir, "file.txt")
	if err := os.WriteFile(existing, []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}

	if !fileExists(existing) {
		t.Error("fileExists returned false for existing file")
	}
	if fileExists(filepath.Join(dir, "missing.txt")) {
		t.Error("fileExists returned true for missing file")
	}
	// Directory is not a regular file.
	if fileExists(dir) {
		t.Error("fileExists returned true for directory")
	}
}

func TestSanitizeOutput(t *testing.T) {
	short := []byte("error: something failed")
	if sanitizeOutput(short) != "error: something failed" {
		t.Errorf("sanitizeOutput modified short output")
	}

	long := make([]byte, 600)
	for i := range long {
		long[i] = 'a'
	}
	result := sanitizeOutput(long)
	if len(result) > 515 {
		t.Errorf("sanitizeOutput did not truncate long output, len=%d", len(result))
	}
}

func TestParseProfileUnsafePermissions(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "wgcf-profile.conf")

	if err := os.WriteFile(path, []byte(sampleProfile), 0o644); err != nil { // #nosec G306
		t.Fatal(err)
	}

	cfg := minimalCfg(path)
	_, err := ParseProfile(cfg)
	if err == nil {
		t.Error("expected error for 0o644 permissions, got nil")
	}
}

func TestParseProfileValid(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "wgcf-profile.conf")

	if err := os.WriteFile(path, []byte(sampleProfile), 0o600); err != nil {
		t.Fatal(err)
	}

	cfg := minimalCfg(path)
	p, err := ParseProfile(cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.IPv4 == "" || p.IPv6 == "" {
		t.Error("profile parsed with empty IP addresses")
	}
}

// minimalCfg returns a config sufficient for ParseProfile without importing
// the config package's Load function.
func minimalCfg(profilePath string) *config.Config {
	return &config.Config{
		Paths: config.Paths{
			WgcfProfileFile: profilePath,
		},
	}
}
